# Generated by Django 6.0.2 on 2026-03-31 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_teacher_specialization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__user_type': 'parent'}, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
